
@baseUrl = http://localhost:4000

@municipio = "Boituva"
@empresa = "EMPRESA DO JOÃO"

//buscando todos os contratos
###
GET {{baseUrl}}/contratos
Content-Type: application/json

//Buscando contratos por um determinado municipio
###
GET {{baseUrl}}/contratos/municipio
Content-Type: application/json

###
GET {{baseUrl}}/empresa
Content-Type: application/json


//inserindo contratos
###
POST {{baseUrl}}/contratos
Content-Type: application/json

{
    "empresa": "Empresa de Fachada",
    "municipio":"Porto Feliz",
    "orgao":"CM",
    "dataInicial":"10/10/2021",
    "dataFinal":"12/12/21",
    "valorMensal": 10.0000,
    "objeto":"Software para Contabilidade"
}