
@baseUrl = http://localhost:4000

//Listar todos os contratos
###
GET {{baseUrl}}/contratos
Content-Type: application/json

//Listar contratos por municipio
###
GET {{baseUrl}}/contratos/municipio/sorocaba
Content-Type: application/json

//Listar contratos por empresa
###
GET {{baseUrl}}/contratos/empresa/empresay
Content-Type: application/json

//Lista contrato por id
###
GET {{baseUrl}}/contratos/id/60af1141da0666397ed1e8ac
Content-Type: application/json

//inserindo 1 contrato
###
POST {{baseUrl}}/contratos
Content-Type: application/json

{
    "empresa": "EmpresaY",
    "municipio":"Porto Feliz",
    "orgao":"CM",
    "dataInicial":"10/10/2021",
    "dataFinal":"12/12/21",
    "valorMensal": 10.0000,
    "objeto":"Software para Contabilidade"
}