//Teste de requisiçoes REST - Empresas

@baseURL = http://localhost:4000
@cnpj = 11111111111113

###
// GET/ - Listar todas as empresas
GET {{baseURL}}/empresas
Content-Type: application/json


###
// GET/empresas/:id - Lista uma empresa por seu id
GET {{baseURL}}/empresas/{{cnpj}}
Content-Type: application/json

{
    "cnpj" : "eeeeeeeeeeeeee"
}

###
//POST - Insere uma nova empresa
POST {{baseURL}}/empresas
Content-Type: application/json

{
    "nome" : "Teste",
    "cnpj" : "44832332899123"
}

###
//PUT - Método para alteração de uma empresa
PUT {{baseURL}}/empresas/{{cnpj}}
Content-Type: application/json

{
    "nome" : "Weg SA",
    "cnpj" : "55555555555556"
}

###
DELETE {{baseURL}}/empresas/{{cnpj}}
Content-Type: Application/json
